name: 'KShop'
version: "@plugin.version@ [@plugin.revision@]"
main: 'ru.kdev.kshop.KShop'
authors: [kdev, WhileInside]

depend:
  - NBTAPI

commands:
  items:
    description: Item list
  shopadmin:
    description: Shop Admin

permissions:
  kshop.admin:
    default: op