connection:
  host: localhost
  user: root
  password: ""
  database: shop
  port: 3306
give-commands:
  give-group: "pex user %player% group set %group%"
locale:
  no-permission: "&cДля этого действия необходим статус &5Админ"
  no-items: "&cКорзина пуста"
  previous: "&aНазад"
  next: "&aВперед"
  close: "&cВыйти"
  admin-help:
    - "&fKShop by &ekdev (Fiwka)"
    - "&f/shopadmin reload - перезагрузить конфиг"
    - "&f/shopadmin add <игрок> <предмет> <количество> [data] [nbt] - добавить предмет игроку"
    - "&f/shopadmin clear <игрок> - очистить корзину игрока"
  gived: "&aПредмет успешно добавлен в корзину игрока %player%!"
  cleared: "&aКорзина игрока %player% успешно очищена"
  next-lore: "&eПеревернуть на следующую страницу"
  previous-lore: "&eПеревернуть назад"
  success-group: "&aВы успешно получили привилегию \"%group%\"!"
  close-lore: "&7Закрыть меню"
  menu-title: "&aПредметы"
  no-args: "&cНедостаточно аргументов."
  wrong-material: "&cНеверный материал."
  wrong-quantity: "&cНеверное количество."
  reload: "&aКонфигурация перезагружена."